from flask import Flask, render_template, request, flash, redirect
from config import  RUCKUS_PASS, RUCKUS_USER, UTC_OFFSET, BASE_URL, DOMAIN_ID
import requests
import urllib3

# Desativa avisos do certificado autoassinado do Ruckus
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
app = Flask(__name__)
app.secret_key = "chave_secreta_para_flash_messages"



def get_ruckus_session():
    session = requests.Session()
    session.verify = False
    auth_data = {
        "username": RUCKUS_USER,
        "password": RUCKUS_PASS,
        "timeZoneUtcOffset": UTC_OFFSET
    }
    try:
        r = session.post(f"{BASE_URL}/session", json=auth_data, timeout=5)
        if r.status_code in [200, 201]:
            return session
    except:
        return None
    return None

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/gerar', methods=['POST'])
def gerar():
    nome = request.form.get('nome')
    cpf = request.form.get('cpf')

    session = get_ruckus_session()
    if not session:
        flash("Erro: Falha de autenticação com o SmartZone.", "danger")
        return redirect('/')

    # ENDPOINT ESPECÍFICO PARA GERAÇÃO DE VOUCHER (GUEST PASS)
    url_voucher = f"{BASE_URL}/identity/guestpass/generate"
    nome_completo = nome+'-'+cpf
    payload = {
        "domainId": DOMAIN_ID,
        "guestName": nome_completo,
        "wlan": {
            "name": "IFCE_Visitantes"
        },
        "zone": {
            "name": "Juazeiro"
        },
        "numberOfPasses": 1,
        "passValidFor": {
            "expirationValue": 1,
            "expirationUnit": "DAY"
        },
        "autoGeneratedPassword": True,
        "passEffectSince": "FIRST_USE",
        "passUseDays": 365,
        "maxDevices": {
            "maxDevicesAllowed": "LIMITED",
            "maxDevicesNumber": 3
        },
        "sessionDuration": {
            "requireLoginAgain": True,
            "sessionValue": 1,
            "sessionUnit": "DAY"
        },
        "remarks": ""
    }


    try:
        res = session.post(url_voucher, json=payload)
        
        if res.status_code == 201:
            dados = res.json()
            user_id = dados.get('id')
            
            # 1. Pequeno delay opcional (0.5s) se o GET abaixo falhar às vezes
            url_user = f"{BASE_URL}/identity/users/{user_id}"
            res_user = session.get(url_user)
            
            if res_user.status_code == 200:
                user_info = res_user.json()
                
                # Usamos .get() encadeado para evitar erro de 'NoneType'
                credentials = user_info.get('credentialsGuestPassDto', {})
                senha = credentials.get('loginPassword')
                
                if senha:
                    print(f"Senha capturada com sucesso: {senha}")
                    return render_template('index.html', voucher=senha, nome=nome)
                else:
                    print("Erro: Usuário criado, mas loginPassword está vazio no JSON.")
                    flash("O acesso foi criado, mas a senha não foi gerada pelo controlador.", "warning")
            else:
                print(f"Erro ao buscar detalhes do usuário ({res_user.status_code}): {res_user.text}")
                flash("Voucher criado, mas erro ao recuperar os detalhes técnicos.", "danger")
        
        else:
            # Caso o POST inicial falhe (ex: cota de vouchers excedida ou erro de rede)
            print(f"Erro Ruckus no POST ({res.status_code}): {res.text}")
            flash(f"Não foi possível criar o voucher. (Erro: {res.status_code})", "danger")

    except Exception as e:
        print(f"Exceção disparada: {str(e)}")
        flash("Ocorreu um erro de comunicação com o servidor do IFCE.", "danger")
    
    # Retorno padrão caso caia em qualquer 'else' ou 'except'
    return redirect('/')

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)
