RUCKUS_IP = "RUCKUS_IP" 
RUCKUS_USER = "RUCKUS_USER"
RUCKUS_PASS = "RUCKUS_PASS"
DOMAIN_ID = "DOMAIN_ID"
ZONE_ID = "ZONE_ID"
WLAN_ID = "WLAN_ID"      # Cole o UUID da IFCE_Visitantes
BASE_URL = f"https://{RUCKUS_IP}:8443/wsg/api/public/v11_0"
UTC_OFFSET = "-03:00"